version: '3.4'

services:
  dockerappexam:
    image: orchestrationexam:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3003:3003
    depends_on:
      - mysql
    links:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: etudiant
      MYSQL_USER: etudiant_user
      MYSQL_PASSWORD: etudiant_password
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: